### ISSUE TITLE
Has a problem with -ve numbers

### ISSUE THREAD

**Issue by andy4us** [jakeboone02/numeric-quantity#3]
I'm using it under node. It works fine for "8 1/2" and returns 8.5. Using "-8 1/2" it is returning -1. I was expecting "-8.5"

**Comment by jakeboone02** [comment]
Yeah, that was on purpose because it was originally for handling recipe quantities, where negative numbers don't make sense. That's why errors return -1. It was an easy hack.

If you feel like submitting a PR to fix it I'd be happy to consider it. I won't be near a computer for a few days, so if you can wait I may take a look next week some time.

**Comment by jakeboone02** [comment]
This is fixed in v0.5.0.
